# Generated by Django 4.1.7 on 2023-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('question', 'Pytanie'), ('other', 'Inne')], max_length=10),
        ),
    ]
